basePath: /v1/auth
definitions:
  entities.LoginReq:
    properties:
      password:
        maxLength: 30
        minLength: 8
        type: string
      username:
        maxLength: 50
        minLength: 5
        type: string
    required:
    - password
    - username
    type: object
  entities.RefreshTokenReq:
    properties:
      token:
        type: string
    required:
    - token
    type: object
  entities.Token:
    properties:
      access_token:
        type: string
      expires_in:
        type: integer
      refresh_token:
        type: string
      type:
        type: string
    type: object
  errors.CustomError:
    properties:
      code:
        type: string
      details:
        items:
          type: string
        type: array
      message:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: ricardo.jonathan.romero@gmail.com
    name: Ricardo Romero
  description: This is the authentication api.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Authentication API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: login customer
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entities.LoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Token'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.CustomError'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/errors.CustomError'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/errors.CustomError'
        "424":
          description: Failed Dependency
          schema:
            $ref: '#/definitions/errors.CustomError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.CustomError'
      security:
      - ApiKeyAuth: []
      summary: Login customer
      tags:
      - auth
  /refresh-token:
    post:
      consumes:
      - application/json
      description: refresh a session using refresh token
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entities.RefreshTokenReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Token'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.CustomError'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/errors.CustomError'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/errors.CustomError'
        "424":
          description: Failed Dependency
          schema:
            $ref: '#/definitions/errors.CustomError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.CustomError'
      security:
      - ApiKeyAuth: []
      summary: Refresh Token
      tags:
      - auth
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: X-Api-Key
    type: apiKey
swagger: "2.0"
